version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "http.host=0.0.0.0"
      - "xpack.security.enabled=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "http.host=0.0.0.0"
      - "xpack.security.enabled=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_USERNAME=admin"
      - "ELASTICSEARCH_PASSWD=admin"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/logs/kibana.log:/var/log/kibana.log
    ports:
        - 5601:5601
    networks:
      - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash:6.7.0
    container_name: logstash
    environment:
      - "XPACK.MONITORING.ELASTICSEARCH.URL=http://elasticsearch:9200"
    networks:
      - esnet

networks:
  esnet:
