server:
  name: kibana
  host: "0.0.0.0"

elasticsearch:
  hosts: http://elasticsearch:9200

xpack:
  graph:
    enabled: true
  watcher:
    enabled: true
  ml:
    enabled: true
  monitoring:
    enabled: true
    ui:
      container:
        elasticsearch:
          enabled: true

logging:
  dest: /var/log/kibana.log
  verbose: true
